\COPY A.Location FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Location.xlsx' DELIMITER ',' CSV;

\COPY A.Carrier FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Carrier.csv' DELIMITER ',' CSV;

\COPY A.Aircraft FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Aircraft.csv' DELIMITER ',' CSV;

\COPY A.Airport FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Airport.csv' DELIMITER ',' CSV;

\COPY A.Aircraft_Details FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Aircraft_Details.csv' DELIMITER ',' CSV;

\COPY A.Flight_Summary FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Flight_Summary.csv' DELIMITER ',' CSV;




\COPY A.Time FROM 'C:\Users\manoj\Desktop\DBSQL\HW4\normalized_tables\Time.csv' DELIMITER ',' CSV;

