\COPY A.Airport FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Airport.csv' DELIMITER ',' CSV;

\COPY A.Aircraft FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Aircraft.csv' DELIMITER ',' CSV;

\COPY A.Carrier FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Carrier.csv' DELIMITER ',' CSV;

\COPY A.Location FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Location.csv' DELIMITER ',' CSV;

\COPY A.Aircraft_Details FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Aircraft_Details.csv' DELIMITER ',' CSV;

\COPY A.Flight_Summary FROM 'C:\Users\manoj\Desktop\DBSQL\airlines_HW\Flight_Summary.csv' DELIMITER ',' CSV;


