\COPY A.Airport FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Airport.csv' DELIMITER ',' CSV;

\COPY A.Aircraft FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Aircraft.csv' DELIMITER ',' CSV;

\COPY A.Carrier FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Carrier.csv' DELIMITER ',' CSV;

\COPY A.Location FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Location.csv' DELIMITER ',' CSV;

\COPY A.Aircraft_Details FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Aircraft_Details.csv' DELIMITER ',' CSV;

\COPY A.Flight_Summary FROM 'C:\Users\manoj\Desktop\DBSQL\HW3\Flight_Summary.csv' DELIMITER ',' CSV;


